authors:
  vedranmiletic:
    name: Vedran Miletić
    description: Principal investigator
    avatar: https://github.com/vedranmiletic.png
    url: https://vedran.miletic.net/
  mateaturalija:
    name: Matea Turalija
    description: PhD student
    avatar: https://github.com/mateaturalija.png
    url: https://mateaturalija.github.io/
  klenkovic:
    name: Kristijan Lenković
    description: GASERI Fan 😎
    avatar: https://github.com/klenkovic.png
    url: https://kristijan.lenkovic.com/
